name: Makefile CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install Requirements
      run: sudo apt install nasm
    - name: make
      run: make all
